# Generated by Django 3.2 on 2021-04-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_mileage'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='users.user'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
    ]
