# Generated by Django 3.2 on 2021-04-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundleoption',
            old_name='price',
            new_name='price_gap',
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='descriptionimage',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='subimage',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
    ]
